### ISSUE TITLE
500 error when trying to log out

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fmn.web#67]
Here's the traceback:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 933, in _verifyDiscoveryResultsOpenID2
    self._verifyDiscoverySingle(endpoint, to_match)
  File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1006, in _verifyDiscoverySingle
    raise TypeURIMismatch(type_uri, endpoint)
TypeURIMismatch: <openid.consumer.consumer.TypeURIMismatch: Required type http://specs.openid.net/auth/2.0/signon not found in ['http://specs.openid.net/auth/2.0/server', 'http://openid.net/server/1.0', 'http://fedoraproject.org/specs/open_id/cla', 'http://ns.launchpad.net/2007/openid-teams', 'http://openid.net/extensions/sreg/1.1', 'http://openid.net/sreg/1.0', 'http://openid.net/srv/ax/1.0', 'http://schemas.openid.net/pape/policies/2007/06/phishing-resistant', 'http://schemas.openid.net/pape/policies/2007/06/multi-factor', 'http://schemas.openid.net/pape/policies/2007/06/multi-factor-physical'] for endpoint <openid.consumer.discover.OpenIDServiceEndpoint server_url='https://id.fedoraproject.org/openid/' claimed_id=None local_id=None canonicalID=None used_yadis=True >>

```

**Comment by ralphbean** [comment]
Seems to work fine now.
